INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Kiłbasa', 1);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Mleko', 12);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Keczup', 2);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Jajka', 1);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Ser żółty', 1);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Jogurty', 6);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Płatki kukurydziane', 1);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Nutella', 1);