# INSERT INTO PRODUCTS (NAME, QUANTITY)
# VALUES ('Kiłbasa', 1);
# INSERT INTO PRODUCTS (NAME, QUANTITY)
# VALUES ('Mleko', 12);
# INSERT INTO PRODUCTS (NAME, QUANTITY)
# VALUES ('Keczup', 2);
# INSERT INTO PRODUCTS (NAME, QUANTITY)
# VALUES ('Jajka', 1);
# INSERT INTO PRODUCTS (NAME, QUANTITY)
# VALUES ('Ser żółty', 1);
# INSERT INTO PRODUCTS (NAME, QUANTITY)
# VALUES ('Jogurty', 6);
# INSERT INTO PRODUCTS (NAME, QUANTITY)
# VALUES ('Płatki kukurydziane', 1);
# INSERT INTO PRODUCTS (NAME, QUANTITY)
# VALUES ('Nutella', 1);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Kiłbasa', 1, 1);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Keczup', 3, 1);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Jajka', 12, 1);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Proszek do prania', 1, 2);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Mydło', 5, 2);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Pasta do zębów', 1, 2);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Płyn zimowy do spryskiwaczy', 1, 3);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Olej', 1, 3);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Wyciskarka do cytrusów', 1, 4);
INSERT INTO PRODUCTS (NAME, QUANTITY, CATEGORY_ID) VALUES ('Kubki', 6, 4);
